version: "3.9"
services:
  postgres:
    container_name: "postgres"
    image: "postgres:9.4-alpine"
    ports:
      - "5432:5432"
    networks:
      - leilao
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "dev-postgres:/var/lib/postgresql/data"

  backend:
    build: .
    container_name: leilao
    ports:
      - "8080:8080"
    networks:
      - leilao
    environment:
      db-url: jdbc:postgresql://postgres:5432/postgres
      db-username: postgres
      db-password: 123
    depends_on:
      - postgres


volumes:
        dev-postgres:

networks:
  leilao:
    driver: bridge
        