apiVersion: v1
kind: Service
metadata:
  name: back-end-leilao
  labels:
    name: back-end-leilao
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: back-end-leilao
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-leilao
  labels:
    app: back-end-leilao
spec:
  replicas: 4
  selector:
    matchLabels:
      app: back-end-leilao
  template:
    metadata:
      labels:
        app: back-end-leilao
    spec:
      containers:
      - name: back-end-leilao
        image: jvgontijo/back-end-leilao:version1.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 1

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: back-end-leilao-service-monitor
spec:
  selector:
    matchLabels:
      app: back-end-leilao
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
      interval: 30s