apiVersion: v1
kind: Pod
metadata:
  name: back-end-leilao-tcp
  labels:
    app: back-end-leilao
spec:
  containers:
  - name: back-end-leilao
    image: jvgontijo/back-end-leilao:version1.0
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
